=== zoozxc456/XML_Practice/ex01/ex01-3.dtd
<!ELEMENT employees (employee*)>
<!ELEMENT employee (name+,age?,sex,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ATTLIST employee 
    id CDATA #REQUIRED
>

=== zoozxc456/XML_Practice/ex01/ex01-3.xml
<?xml version="1.0" encoding=" UTF-8"?>
<!DOCTYPE employees SYSTEM "ex01-3.dtd">
<employees>
    <employee id="1">
        <name>張三</name>
        <age>32</age>
        <sex>男</sex>
        <address>台中</address>
    </employee>
    <employee id="2">
        <name>李四</name>
        <age>22</age>
        <sex>男</sex>
        <address>新竹</address>
    </employee>
</employees>
