=== zoozxc456/XML_Practice/ex03/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-2 XSD -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" type="employee_type" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="employee_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="age" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element name="sex" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="address" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="pid" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]\d{9}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== zoozxc456/XML_Practice/ex03/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-2 XML -->
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <employee pid="B123456789">
        <name>張三</name>
        <age>32</age>
        <sex>男</sex>
        <address>台中</address>
    </employee>
    <employee pid="P234567891">
        <name>李四</name>
        <age>22</age>
        <sex>男</sex>
        <address>新竹</address>
    </employee>
</employees>
