=== zoozxc456/XML_Practice/ex03/inventory-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-4 XSD -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventory">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="price" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="quantity" type="xs:int"></xs:element>
                                <xs:element name="available" type="xs:date"></xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="isbn">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{1}-\d{2}-\d{6}-\d{1}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="inStock">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="yes" />
                                    <xs:enumeration value="no" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zoozxc456/XML_Practice/ex03/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- File name : inventory.xml -->
<!-- ex03-4 XML -->
<inventory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="inventory-schema.xsd">
    <book isbn="0-12-012507-8" inStock="yes">
        <name> How to program in Java 3/e</name>
        <price>USD88</price>
        <quantity>300</quantity>
    </book>
    <book isbn="0-12-028418-5" inStock="no">
        <name>XML and Web Service</name>
        <price>USD68 </price>
        <available>2015-12-15</available>
    </book>
</inventory>
