=== zoozxc456/XML_Practice/ex03/product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-6 XSD -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PRODUCTDATA" type="prdata" />

    <xs:complexType name="prdata">
        <xs:sequence>
            <xs:element name="PRODUCT" type="prdt"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="prdt">
        <xs:sequence>
            <xs:element name="PRODUCTNAME" type="xs:string" />
            <xs:element name="DESCRIPTION" type="xs:string" />
            <xs:element name="PRICE" type="xs:decimal" minOccurs="3" maxOccurs="5" />
            <xs:element name="QUANTITY" type="xs:integer" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== zoozxc456/XML_Practice/ex03/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-6 XML -->
<PRODUCTDATA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="product.xsd">
    <PRODUCT>
        <PRODUCTNAME>hello</PRODUCTNAME>
        <DESCRIPTION>nice</DESCRIPTION>
        <PRICE>100.0</PRICE>
        <PRICE>200.59</PRICE>
        <PRICE>23.9994</PRICE>
        <QUANTITY>194</QUANTITY>
    </PRODUCT>
</PRODUCTDATA>
