=== zoozxc456/XML_Practice/ex03/textbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-5 XSD -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="booklist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bookTitle" type="xs:string"></xs:element>
                            <xs:element name="pubDate" type="xs:date"></xs:element>
                            <xs:element name="authorlist">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="author" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="price" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="ISBN">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{3}-\d{3}-\d{3}-\d{3}-\d{1}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zoozxc456/XML_Practice/ex03/textbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ex03-5 XML -->
<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="textbook.xsd">
    <book ISBN="966-788-611-147-9">
        <bookTitle>DBMS Using SQL Server 2015</bookTitle>
        <pubDate>2015-08-30</pubDate>
        <authorlist>
            <author>潔西卡</author>
        </authorlist>
        <price>NT780</price>
    </book>
    <book ISBN="966-788-622-146-5">
        <bookTitle>Java 8 語言入門</bookTitle>
        <pubDate>2015-07-12</pubDate>
        <authorlist>
            <author>威爾遜</author>
        </authorlist>
        <price> NT 700</price>
    </book>
    <book ISBN="966-788-244-127-2">
        <bookTitle>Java 8 語言指引</bookTitle>
        <pubDate>2015-11-25</pubDate>
        <authorlist>
            <author>尼爾森</author>
        </authorlist>
        <price> NT 750</price>
    </book>
</booklist>
